### ISSUE TITLE
Cannot download JavaScript library from the GitHub server when publishing the graph online

### ISSUE THREAD

**Issue by dimonoid** [mpld3/mpld3#467] opened 2020-06-19 20:22 UTC

**Comment by dimonoid** [comment] 2020-06-19 20:23
This happens only with the latest version

**Comment by ezralangelo** [comment] 2020-06-22 05:18
same with me, it says failed to load library on mpld3 version 0.5 and 0.5.1

**Comment by ezralangelo** [comment] 2020-06-22 05:19
and i clicked on the library url https://mpld3.github.io/js/mpld3.v0.5.1.js and its error404

**Comment by dimonoid** [comment] 2020-06-22 05:21
I actually solved it by adding additional parameters into the function generating the html to load the libraries from the local server. See help for details.

**Comment by ezralangelo** [comment] 2020-06-22 05:30
hello can you explain more about this?
are you using mpld3.fig_to_html function? which parameters do you add the the function?

**Comment by ckerr-IDM** [comment] 2020-06-22 05:34
Thanks @dimonoid and @ezralangelo -- we'll look into it and hopefully get it fixed shortly!

**Comment by duerrsimon** [comment] 2020-06-24 08:26
Looks to me like your gh-pages branch is not up to date anymore. Latest commit there is a few years ago so this seems off. 

In the mean time for anyone looking to fix this: Go to https://github.com/mpld3/mpld3/tree/master/mpld3/js and download the latest version as min file. Replace the path to mpld3.github.io in your html file with the path pointing to this file. 

Afaik one is not supposed to use github pages as CDN. Maybe in the future you might want to host the latest version of the mpld3 library on a proper cdn like cdnjs https://github.com/cdnjs/packages#become-a-contributor

**Comment by vladh** [comment] 2020-06-26 23:00
Hey guys,

Thank you for writing about this issue. @duerrsimon is right — the website needs to be updated, and the JS file needs to be uploaded to a proper CDN. I'm working on making time for this ASAP. I hope to have it done within the next couple of days. In the meantime, please use the fix @duerrsimon suggested.

Thank you for your patience!

**Comment by vladh** [comment] 2020-06-27 20:02
Thank you for your patience, everyone, and sorry for the wait. I've now updated the JS files on the website, so the normal export process should work! I'll look into using a proper CDN soon. Please let me know if everything works or if you still have issues!

**Comment by jannisborn** [comment] 2021-07-20 13:05
Hey @vladh is there any progress on this issue?

**Comment by vladh** [comment] 2021-07-20 13:23
@jannisborn I fixed the issue but accidentally didn't close it — are you still having this problem? If so, could you let me know what the problematic URL is?

**Comment by jannisborn** [comment] 2021-07-20 13:38
I have a `.html` produced in spring 2020 with `fig_to_html` and version `0.3.1`. The file does not render anymore (white screen only) and I'm 100% sure the file rendered properly when I created it. 
I thought that it can only be related to the js library version (I use `d3.v3.min` and `mpld3.v0.3.1.dev1.js` but both are accessible via your github-CDN, so it's not really related to this issue). Do you have any idea what might be the cause? Thanks a lot!

The file is [here](https://github.com/PaccMann/paccmann.github.io/blob/master/assets/tox21_attention_maps.html)

**Comment by vladh** [comment] 2021-07-21 20:22
Hey @jannisborn! I've looked into your issue, and while I can't say exactly why code that was working before isn't working anymore, it seems like you are using a version of mpld3 that requires d3 v5, but you're loading d3 v3.

A simple fix is to replace `https://mpld3.github.io/js/d3.v3.min.js` with, for example, `https://cdnjs.cloudflare.com/ajax/libs/d3/5.0.0/d3.min.js` in your code. I did this and your graph renders for me. I would also recommend updating to the latest version of mpld3 — I can't think of any breaking changes off the top of my head.

Hope that helped!

**Closed by vladh** 2021-07-21 20:22 UTC
Labels: enhancement

**Comment by jannisborn** [comment] 2021-07-21 21:18
It works! Fantastic, many many thanks @vladh :)
My guess was that it's indeed related to the version. I've updated the package now to the latest version. I produced this figure last year and now I'm lacking the source code to redo it. With this fix you really saved my butt. Lmk if I can buy you a coffee!
