### ISSUE TITLE
compatibility with vscode debugging?

### ISSUE THREAD

**Issue by seyeeet** [mpld3/mpld3#503] opened 2021-11-18 15:10 UTC
Hello
I was surprise how amazing this package is, for vscode users it is almost impossible to visualize a file when they are in the debug mode and ssh connecting to server. one solution is trying to X forwarding and setting the display but that is painful and not working well.
Another solution is to save what you want to visualize and then display it in non debug mode.
And NOW another solution is using mpld3d, I simply could do `mpld3.show()` and a window opens in my laptop in browser and showed the image!!! Super excited...
There is one concern though at the moment, it is supper slow (taking forever) for an image in size of `128x128x3` for very small samples like what we have in the tutorial like 
```
plt.plot([3,1,4,1,5], 'ks-', mec='w', mew=5, ms=20)
mpld3.show()
```
 it is okay (not fast but okay).
I was wondering if it can be somehow improved for larger images? or if you have any suggestion in general?
Thanks

**Comment by vladh** [comment] 2021-11-23 14:34
Hey @seyeeet, it's not 100% clear to me what the issue is. As far as I understand, the issue is less about VS Code, and more about running scripts over an SSH connection? Regarding the performance issue you're seeing, is that tied to running this script remotely somehow, or is it slow if you run it locally in the normal way?

Either way, if you have a specific issue or suggestion, feel free to open a more precise ticket, but I'll close this ticket for now.

**Closed by vladh** 2021-11-23 14:34 UTC

**Comment by seyeeet** [comment] 2021-11-23 15:47
yes, I think it is more about running scripts over an SSH connection, it becomes very slow for large files to display, for for now I am not sure how to deal with it. I think there is not a clear way to do it anyways
